// <auto-generated />
using System;
using Backend.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Backend.Migrations
{
    [DbContext(typeof(ApotekaContext))]
    [Migration("20220118213545_v4.9")]
    partial class v49
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Backend.Models.Apoteka", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresa")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Adresa");

                    b.Property<string>("Naziv")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Naziv");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Opis");

                    b.HasKey("ID");

                    b.ToTable("Apoteka");
                });

            modelBuilder.Entity("Backend.Models.Klijent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("Email");

                    b.Property<string>("Password")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Password");

                    b.Property<string>("Username")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("Username");

                    b.HasKey("ID");

                    b.ToTable("Klijent");
                });

            modelBuilder.Entity("Backend.Models.Lek", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApotekaID")
                        .HasColumnType("int");

                    b.Property<double>("Cena")
                        .HasColumnType("float")
                        .HasColumnName("Cena");

                    b.Property<string>("Opis")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Opis");

                    b.HasKey("ID");

                    b.HasIndex("ApotekaID");

                    b.ToTable("Lek");
                });

            modelBuilder.Entity("Backend.Models.Recept", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DatumDo")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatumDo");

                    b.Property<DateTime>("DatumOd")
                        .HasColumnType("datetime2")
                        .HasColumnName("DatumOd");

                    b.Property<int?>("KlijentID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("KlijentID");

                    b.ToTable("Recept");
                });

            modelBuilder.Entity("LekRecept", b =>
                {
                    b.Property<int>("LekoviID")
                        .HasColumnType("int");

                    b.Property<int>("ReceptiID")
                        .HasColumnType("int");

                    b.HasKey("LekoviID", "ReceptiID");

                    b.HasIndex("ReceptiID");

                    b.ToTable("LekRecept");
                });

            modelBuilder.Entity("Backend.Models.Lek", b =>
                {
                    b.HasOne("Backend.Models.Apoteka", "Apoteka")
                        .WithMany("Lekovi")
                        .HasForeignKey("ApotekaID");

                    b.Navigation("Apoteka");
                });

            modelBuilder.Entity("Backend.Models.Recept", b =>
                {
                    b.HasOne("Backend.Models.Klijent", "Klijent")
                        .WithMany("Recepti")
                        .HasForeignKey("KlijentID");

                    b.Navigation("Klijent");
                });

            modelBuilder.Entity("LekRecept", b =>
                {
                    b.HasOne("Backend.Models.Lek", null)
                        .WithMany()
                        .HasForeignKey("LekoviID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Recept", null)
                        .WithMany()
                        .HasForeignKey("ReceptiID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Backend.Models.Apoteka", b =>
                {
                    b.Navigation("Lekovi");
                });

            modelBuilder.Entity("Backend.Models.Klijent", b =>
                {
                    b.Navigation("Recepti");
                });
#pragma warning restore 612, 618
        }
    }
}
